---
slug: conversational-python
filename: conversational-python
title: Conversational Python
subtitle: An Introduction to Computer Science Experienced Through
 Conversational Banter
description:
author: Jason B. Shepherd, Ph.D.
copyright: 2017
uuid: 26ac1544-7fa3-4545-8ea3-7f6343a9ef72
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
