---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        * Optimized for computer screens, Kindle, and iPad
        * A textbook for students who don't like textbooks
    media:
      - ebooks
    price: 2500

authors:
  -
    name: "Jason B. Shepherd, Ph.D."
    gravatar_email: "jbshep@gmail.com"
    contact_email: "jason_b_shepherd@acm.org"
    contact_twitter: "@jbshep"
    contact_fb: "http://facebook.com/jbshep"
    bio:
      |
        Author bio [link](https://jbshep.github.io)

marketing_content: ''

repo_url: ''
contact_email: 'jason_b_shepherd@acm.org'
hide_custom_domain_footer: false
